version: "3"
services:
  pwn:
    container_name: pwn
    image: y011d4/pwndocker
    volumes:
      - "/home/y011d4:/ctf/work"
    cap_add:
      - SYS_PTRACE
    # ports:
    #   - "23946:23946"
    security_opt:
      - seccomp:unconfined
    command: sleep infinity
